backend:
  name: git-gateway
  branch: main

collections:
  - name: "news"
    label: "Actualités"
    folder: "content/news"
    create: true
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Contenu", widget: "markdown" }
